"""
Ultralytics YOLO-pose label formatting & parsing (bpy-FREE, Docker-testable).

Label line (spec §3.9), one per labeled card:

    class cx cy w h  x1 y1 v1  x2 y2 v2  x3 y3 v3  x4 y4 v4  |<card_id>

- All coords normalized to [0,1], image top-left origin.
- bbox (cx,cy,w,h) = min/max envelope of the four corner keypoints.
- Keypoints in FIXED order (config.KEYPOINT_ORDER, default TL,TR,BR,BL) in the
  card's own upright frame; visibility flag = 2 for all four.
- The trailing ` |<card_id>` is our extension. A "strictly standard" variant
  (no suffix) can be emitted into a sibling folder via include_id=False.

The Blender side computes the four normalized corners (with Y already flipped to
top-left origin) and hands them here; this module never touches bpy.
"""
from __future__ import annotations

import os
from dataclasses import dataclass
from typing import List, Sequence, Tuple

try:
    import config
except ImportError:  # pragma: no cover
    from .. import config  # type: ignore

Corner = Tuple[float, float]  # (x, y) normalized, top-left origin


def _fmt(v: float) -> str:
    """6-decimal fixed format; keeps label files diff-stable and compact."""
    return f"{v:.6f}"


def bbox_from_corners(corners: Sequence[Corner]) -> Tuple[float, float, float, float]:
    """Return (cx, cy, w, h) normalized, as the min/max envelope of corners."""
    xs = [c[0] for c in corners]
    ys = [c[1] for c in corners]
    x0, x1 = min(xs), max(xs)
    y0, y1 = min(ys), max(ys)
    return ((x0 + x1) / 2.0, (y0 + y1) / 2.0, x1 - x0, y1 - y0)


@dataclass(frozen=True)
class CardLabel:
    """One card instance's label data (already normalized, top-left origin)."""
    card_id: str
    corners: Tuple[Corner, Corner, Corner, Corner]  # in KEYPOINT_ORDER
    class_id: int = config.YOLO_CLASS_ID
    visibility: int = config.KPT_VISIBILITY

    def to_line(self, include_id: bool = True) -> str:
        cx, cy, w, h = bbox_from_corners(self.corners)
        parts: List[str] = [str(self.class_id), _fmt(cx), _fmt(cy), _fmt(w), _fmt(h)]
        for (x, y) in self.corners:
            parts.extend([_fmt(x), _fmt(y), str(int(self.visibility))])
        line = " ".join(parts)
        if include_id:
            line += f" |{self.card_id}"
        return line


@dataclass(frozen=True)
class ParsedLabel:
    """Result of parsing one label line (for the visualizer / validation)."""
    class_id: int
    bbox: Tuple[float, float, float, float]           # cx, cy, w, h
    corners: List[Corner]
    visibilities: List[int]
    card_id: str  # "" if the line had no |id suffix


def parse_pose_line(line: str) -> ParsedLabel:
    """Parse one label line, tolerating the optional trailing ` |<card_id>`."""
    line = line.strip()
    card_id = ""
    if "|" in line:
        line, card_id = line.rsplit("|", 1)
        card_id = card_id.strip()
    toks = line.split()
    class_id = int(float(toks[0]))
    cx, cy, w, h = (float(t) for t in toks[1:5])
    kpt_toks = toks[5:]
    corners: List[Corner] = []
    vis: List[int] = []
    for i in range(0, len(kpt_toks), 3):
        x, y = float(kpt_toks[i]), float(kpt_toks[i + 1])
        v = int(float(kpt_toks[i + 2])) if i + 2 < len(kpt_toks) else 2
        corners.append((x, y))
        vis.append(v)
    return ParsedLabel(class_id, (cx, cy, w, h), corners, vis, card_id)


def write_label_file(path: str, labels: Sequence[CardLabel], include_id: bool = True) -> None:
    """Write one line per label. Empty list => empty file (still written, so a
    rendered image always has its label pair, even when 0 cards are labeled)."""
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        for lab in labels:
            fh.write(lab.to_line(include_id=include_id) + "\n")


def write_dataset_yaml(
    path: str,
    train: str = "images",
    val: str = "images",
    class_names: Sequence[str] = ("card",),
) -> None:
    """Write an Ultralytics dataset.yaml with kpt_shape [4, 3] (spec §3.9).

    Written by hand (no PyYAML dependency) to keep this module dependency-free.
    """
    kx, ky = config.KPT_SHAPE
    names = "\n".join(f"  {i}: {n}" for i, n in enumerate(class_names))
    content = (
        f"# Auto-generated by labeltools/yolo_pose.py\n"
        f"path: .\n"
        f"train: {train}\n"
        f"val: {val}\n"
        f"kpt_shape: [{kx}, {ky}]\n"
        f"# keypoint order: {', '.join(config.KEYPOINT_ORDER)} (card's own upright frame)\n"
        f"names:\n{names}\n"
    )
    os.makedirs(os.path.dirname(os.path.abspath(path)) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
