"""
Card surface finishes (bpy REQUIRED). Spec §3.4 + user comparison request.

Holo foil is a diffraction grating; Blender can't simulate diffraction directly, so
we provide TWO approaches to compare (render the same card at multiple angles to see
the COLOUR shift with view angle, not just brightness):

  (1) thin-film  : metallic base + Principled "Thin Film Thickness" driven across
                   ~100-1500nm by the holo pattern texture, "Thin Film IOR" ~1.45.
                   Physically-based iridescence (Cycles supports it; EEVEE Next also).
  (2) spectral   : dot(perturbed Normal, Incoming) -> spectral Color Ramp; the angle
                   input is perturbed per-pixel by the pattern so hue varies spatially.
                   Faked goniochromism.

In BOTH the pattern NORMAL map perturbs the shading normal so the etched texture
bends the rainbow. For 'horizontal_lines' we also add anisotropic specular with the
Anisotropic Rotation following the line direction.

The holo REGION (entire/picture/reverse) is a procedural UV-box mask that mixes the
foil against a plain card shader. Pattern + pattern-normal images are generated by
texturegen/holo.py (cv2) and passed in as paths.
"""
from __future__ import annotations

import os
from typing import Optional, Tuple

import bpy

import config

THIN_FILM_MIN_NM = 100.0
THIN_FILM_MAX_NM = 1500.0
THIN_FILM_IOR = 1.45

_TWO_PI = 6.28318530718
# Diffraction-flash holo tuning lives in config.json ["holo"] (config.load_holo_tuning);
# loaded at material-build time so it can be tuned without editing code.


# --------------------------------------------------------------------------- #
# Small node helpers
# --------------------------------------------------------------------------- #
def _value(nt, v: float):
    n = nt.nodes.new("ShaderNodeValue")
    n.outputs[0].default_value = v
    return n.outputs[0]


def _is_socket(x) -> bool:
    return hasattr(x, "node") and hasattr(x, "links")


def _math(nt, op: str, a, b=None, clamp=False):
    n = nt.nodes.new("ShaderNodeMath")
    n.operation = op
    n.use_clamp = clamp
    nt.links.new(a, n.inputs[0])
    if b is not None:
        if _is_socket(b):
            nt.links.new(b, n.inputs[1])
        else:
            n.inputs[1].default_value = float(b)
    return n.outputs[0]


def _uv_components(nt):
    coord = nt.nodes.new("ShaderNodeTexCoord")
    sep = nt.nodes.new("ShaderNodeSeparateXYZ")
    nt.links.new(coord.outputs["UV"], sep.inputs[0])
    v_td = _math(nt, "SUBTRACT", _value(nt, 1.0), sep.outputs["Y"])  # 1 - v (top-down)
    return sep.outputs["X"], v_td


def _region_mask(nt, region: Tuple[float, float, float, float], mode: str):
    if mode == "entire":
        return _value(nt, 1.0)
    x0, y0, x1, y1 = region
    u, v_td = _uv_components(nt)
    inside = _math(nt, "MULTIPLY",
                   _math(nt, "MULTIPLY", _math(nt, "GREATER_THAN", u, x0),
                         _math(nt, "LESS_THAN", u, x1)),
                   _math(nt, "MULTIPLY", _math(nt, "GREATER_THAN", v_td, y0),
                         _math(nt, "LESS_THAN", v_td, y1)))
    if mode == "picture":
        return inside
    if mode == "reverse":
        return _math(nt, "SUBTRACT", _value(nt, 1.0), inside)
    raise ValueError(f"bad holo region mode {mode!r}")


def _image_tex(nt, path: str, non_color: bool):
    tex = nt.nodes.new("ShaderNodeTexImage")
    img = bpy.data.images.load(path, check_existing=True)
    if non_color:
        img.colorspace_settings.name = "Non-Color"
    tex.image = img
    return tex


def _pattern_normal(nt, pattern_normal_path: Optional[str], strength: float = 0.6):
    """Return the perturbed-Normal socket from the pattern normal map, or None."""
    if not pattern_normal_path or not os.path.isfile(pattern_normal_path):
        return None
    tex = _image_tex(nt, pattern_normal_path, non_color=True)
    nmap = nt.nodes.new("ShaderNodeNormalMap")
    nmap.inputs["Strength"].default_value = strength
    nt.links.new(tex.outputs["Color"], nmap.inputs["Color"])
    return nmap.outputs["Normal"]


def _rgb(nt, rgb):
    n = nt.nodes.new("ShaderNodeRGB")
    n.outputs[0].default_value = (rgb[0], rgb[1], rgb[2], 1.0)
    return n.outputs[0]


def _mix_rgb(nt, fac, color_a, color_b):
    """MixColor (RGBA) node -> Result color socket. color_a/color_b are sockets."""
    m = nt.nodes.new("ShaderNodeMix")
    m.data_type = "RGBA"
    nt.links.new(fac, m.inputs[0])          # Factor
    nt.links.new(color_a, m.inputs[6])      # A (color)
    nt.links.new(color_b, m.inputs[7])      # B (color)
    return m.outputs[2]                      # Result (color)


def _base_card_bsdf(nt, card_image_path: Optional[str]):
    """Plain glossy card shader (used outside the holo region)."""
    bsdf = nt.nodes.new("ShaderNodeBsdfPrincipled")
    bsdf.inputs["Roughness"].default_value = 0.3
    bsdf.inputs["Coat Weight"].default_value = 0.3
    bsdf.inputs["Coat Roughness"].default_value = 0.05
    if card_image_path and os.path.isfile(card_image_path):
        tex = _image_tex(nt, card_image_path, non_color=False)
        nt.links.new(tex.outputs["Color"], bsdf.inputs["Base Color"])
    else:
        bsdf.inputs["Base Color"].default_value = (0.5, 0.5, 0.5, 1.0)
    return bsdf


def _apply_anisotropy(nt, bsdf, pattern_name: str):
    """For line patterns, anisotropic specular aligned to the line direction."""
    if pattern_name == "horizontal_lines":
        bsdf.inputs["Anisotropic"].default_value = 0.8
        # Horizontal lines run along the U/tangent; 0.0 keeps the streak along it.
        bsdf.inputs["Anisotropic Rotation"].default_value = 0.0


def _finalize(nt, base_bsdf, foil_bsdf, mask):
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    mix = nt.nodes.new("ShaderNodeMixShader")
    nt.links.new(mask, mix.inputs[0])          # 0 -> base, 1 -> foil
    nt.links.new(base_bsdf.outputs["BSDF"], mix.inputs[1])
    nt.links.new(foil_bsdf.outputs["BSDF"], mix.inputs[2])
    nt.links.new(mix.outputs[0], out.inputs["Surface"])


# --------------------------------------------------------------------------- #
# Public materials
# --------------------------------------------------------------------------- #
def make_normal_material(name: str, card_image_path: Optional[str],
                         physical_normal_path: Optional[str] = None):
    """Plain glossy (non-holo) card."""
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nt = mat.node_tree
    nt.nodes.clear()
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    bsdf = _base_card_bsdf(nt, card_image_path)
    sock = _pattern_normal(nt, physical_normal_path, strength=0.5)
    if sock is not None:
        nt.links.new(sock, bsdf.inputs["Normal"])
    nt.links.new(bsdf.outputs["BSDF"], out.inputs["Surface"])
    return mat


def make_holo_thinfilm(name: str, card_image_path: Optional[str],
                       pattern_img_path: str, pattern_normal_path: Optional[str],
                       picture_region, region_mode: str, pattern_name: str, seed: int = 0):
    """Version 1 — physically-based thin-film iridescence."""
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nt = mat.node_tree
    nt.nodes.clear()

    base = _base_card_bsdf(nt, card_image_path)

    foil = nt.nodes.new("ShaderNodeBsdfPrincipled")
    foil.inputs["Metallic"].default_value = 1.0
    foil.inputs["Roughness"].default_value = 0.15
    if card_image_path and os.path.isfile(card_image_path):
        nt.links.new(_image_tex(nt, card_image_path, False).outputs["Color"],
                     foil.inputs["Base Color"])
    # Thin film thickness = pattern value mapped to [min,max] nm.
    pat = _image_tex(nt, pattern_img_path, non_color=True)
    mr = nt.nodes.new("ShaderNodeMapRange")
    mr.inputs["To Min"].default_value = THIN_FILM_MIN_NM
    mr.inputs["To Max"].default_value = THIN_FILM_MAX_NM
    nt.links.new(pat.outputs["Color"], mr.inputs["Value"])
    nt.links.new(mr.outputs["Result"], foil.inputs["Thin Film Thickness"])
    foil.inputs["Thin Film IOR"].default_value = THIN_FILM_IOR
    # Pattern normal bends the interference.
    nsock = _pattern_normal(nt, pattern_normal_path)
    if nsock is not None:
        nt.links.new(nsock, foil.inputs["Normal"])
    _apply_anisotropy(nt, foil, pattern_name)

    _finalize(nt, base, foil, _region_mask(nt, picture_region, region_mode))
    return mat


def _spectral_ramp(nt):
    ramp = nt.nodes.new("ShaderNodeValToRGB")
    el = ramp.color_ramp.elements
    stops = [(0.00, (1.0, 0.0, 0.0)), (0.17, (1.0, 0.8, 0.0)), (0.33, (0.0, 1.0, 0.1)),
             (0.50, (0.0, 0.9, 1.0)), (0.67, (0.1, 0.2, 1.0)), (0.83, (0.8, 0.0, 1.0)),
             (1.00, (1.0, 0.0, 0.4))]
    el[0].position, el[0].color = stops[0][0], (*stops[0][1], 1.0)
    el[1].position, el[1].color = stops[-1][0], (*stops[-1][1], 1.0)
    for pos, col in stops[1:-1]:
        e = el.new(pos)
        e.color = (*col, 1.0)
    return ramp


def make_holo_spectral(name: str, card_image_path: Optional[str],
                       pattern_img_path: str, pattern_normal_path: Optional[str],
                       picture_region, region_mode: str, pattern_name: str, seed: int = 0,
                       physical_normal_path: Optional[str] = None):
    """Version 2 — DIFFRACTION-FLASH holo (angle-selective, thresholded).

    Real holo is a diffraction grating: only regions whose local structure aligns the
    view flash rainbow at any given angle; the rest just slightly darkens the base, and
    the flashing regions shift as the angle changes. Model:
      phase P = facing*ANGLE_GAIN + pattern*PATTERN_GAIN   (facing = dot(N, Incoming))
      flash f = pow(0.5 + 0.5*cos(P*2pi), SHARPNESS)       (narrow, mostly dark)
      hue     = FRACT(P) -> spectral ramp
      base    = art, darkened between flashes; emission = ramp*f (localised, no washout)
    Responds to CAMERA/CARD angle (surface shaders can't read light directions).
    Only the LINE pattern is physically raised (pattern normal -> shading normal)."""
    tune = config.load_holo_tuning()
    angle_gain = tune["angle_gain"]
    pattern_gain = tune["pattern_gain"]
    sharpness = tune["sharpness"]
    emit = tune["emit"]
    darken = tune["darken"]

    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nt = mat.node_tree
    nt.nodes.clear()
    out = nt.nodes.new("ShaderNodeOutputMaterial")

    bsdf = nt.nodes.new("ShaderNodeBsdfPrincipled")
    bsdf.inputs["Roughness"].default_value = 0.18
    bsdf.inputs["Coat Weight"].default_value = 0.4
    bsdf.inputs["Coat Roughness"].default_value = 0.05

    # Raised shading normal: the §3.4 physical-texture (etched foil) if provided is the
    # main raised layer; otherwise only the LINE pattern is raised (flat holo patterns
    # stay flat -> no fake bumps).
    phys = _pattern_normal(nt, physical_normal_path, strength=0.6) if physical_normal_path else None
    line_n = (_pattern_normal(nt, pattern_normal_path)
              if (pattern_name == "horizontal_lines" and phys is None) else None)
    nsock = phys if phys is not None else line_n
    if nsock is not None:
        nt.links.new(nsock, bsdf.inputs["Normal"])

    # facing = dot(N, Incoming) -> shifts with view/card angle.
    geom = nt.nodes.new("ShaderNodeNewGeometry")
    dot = nt.nodes.new("ShaderNodeVectorMath")
    dot.operation = "DOT_PRODUCT"
    nt.links.new(nsock if nsock is not None else geom.outputs["Normal"], dot.inputs[0])
    nt.links.new(geom.outputs["Incoming"], dot.inputs[1])

    pat = _image_tex(nt, pattern_img_path, non_color=True)
    # phase P = facing*angle_gain + pattern*pattern_gain
    phase = _math(nt, "ADD",
                  _math(nt, "MULTIPLY", dot.outputs["Value"], angle_gain),
                  _math(nt, "MULTIPLY", pat.outputs["Color"], pattern_gain))
    # flash f = pow(0.5 + 0.5*cos(P*2pi), sharpness)
    band = _math(nt, "ADD",
                 _math(nt, "MULTIPLY",
                       _math(nt, "COSINE", _math(nt, "MULTIPLY", phase, _TWO_PI)), 0.5), 0.5)
    flash = _math(nt, "POWER", band, sharpness)
    # hue = FRACT(P) -> spectral ramp
    ramp = _spectral_ramp(nt)
    nt.links.new(_math(nt, "FRACT", phase), ramp.inputs["Fac"])

    mask = _region_mask(nt, picture_region, region_mode)

    # Base = art, slightly darkened between flashes (in region): mix art->black by
    # mask * DARKEN * (1 - flash).
    art = (_image_tex(nt, card_image_path, False).outputs["Color"]
           if card_image_path and os.path.isfile(card_image_path) else _rgb(nt, (0.5, 0.5, 0.5)))
    darkfac = _math(nt, "MULTIPLY", _math(nt, "MULTIPLY", mask, darken),
                    _math(nt, "SUBTRACT", _value(nt, 1.0), flash))
    nt.links.new(_mix_rgb(nt, darkfac, art, _rgb(nt, (0.0, 0.0, 0.0))),
                 bsdf.inputs["Base Color"])

    # Localised rainbow flash as emission: strength = mask * flash * emit.
    nt.links.new(ramp.outputs["Color"], bsdf.inputs["Emission Color"])
    nt.links.new(_math(nt, "MULTIPLY", _math(nt, "MULTIPLY", mask, flash), emit),
                 bsdf.inputs["Emission Strength"])

    _apply_anisotropy(nt, bsdf, pattern_name)
    nt.links.new(bsdf.outputs["BSDF"], out.inputs["Surface"])
    return mat


def make_holo(name: str, version: str, card_image_path, pattern_img_path,
              pattern_normal_path, picture_region, region_mode, pattern_name, seed=0,
              physical_normal_path=None):
    if version == "thinfilm":
        return make_holo_thinfilm(name, card_image_path, pattern_img_path,
                                  pattern_normal_path, picture_region, region_mode,
                                  pattern_name, seed)
    if version == "spectral":
        return make_holo_spectral(name, card_image_path, pattern_img_path,
                                  pattern_normal_path, picture_region, region_mode,
                                  pattern_name, seed, physical_normal_path=physical_normal_path)
    raise ValueError(f"bad holo version {version!r}")
